databases:
  - name: task-app
    databaseName: task-app
    user: task-app
    plan: free

services:
  - type: web
    name: task-app
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2